/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2019-06-27 17:09:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;

public final class nou_005fDosar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" type=\"text/css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://static.pingendo.com/bootstrap/bootstrap-4.1.3.css\">\n");
      out.write("</head>\n");
      db.JavaBean jb = null;
      synchronized (session) {
        jb = (db.JavaBean) _jspx_page_context.getAttribute("jb", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (jb == null){
          jb = new db.JavaBean();
          _jspx_page_context.setAttribute("jb", jb, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("jb"), request);
      out.write("\n");
      out.write("\n");
      out.write("<body style=\"\tbackground-image: url(/images/yannis-papanastasopoulos-yWF2LLan-_o-unsplash.jpg);\tbackground-position: top left;\tbackground-size: 100%;\tbackground-repeat: repeat;\">\n");
      out.write("  <nav class=\"navbar navbar-expand-md navbar-dark bg-dark\">\n");
      out.write("    <div class=\"container\"> <button class=\"navbar-toggler navbar-toggler-right border-0\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar13\">\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("      </button>\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbar13\"> <a class=\"navbar-brand d-none d-md-block\" href=\"index.html\">\n");
      out.write("          <i class=\"fa fa-users\"></i>\n");
      out.write("          <b> ACASA</b>\n");
      out.write("        </a>\n");
      out.write("        <ul class=\"navbar-nav mx-auto\">\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link\" href=\"tabela_Angajati.jsp\">Concerte</a> </li>\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link\" href=\"tabela_Reviweuri.jsp\">Reviewuri</a> </li>\n");
      out.write("          <li class=\"nav-item\"> <a class=\"nav-link\" href=\"tabela_Dosar.jsp\">Dosare</a> </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("              \n");
      out.write("  </nav>\n");
      out.write("  <div class=\"py-5\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("          <h5 class=\"bg-dark text-light w-100\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Formular adaugare dosar</h5>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("    ");

            int idangajat, idreview;
            String id1, id2, NumeAngajat, PrenumeAngajat, Firma, Experienta, tipReview, comentariiReview, detinator, datacreare;
            id1 = request.getParameter("idangajat");
            id2 = request.getParameter("idreview");
            datacreare = request.getParameter("datacreare");
            detinator = request.getParameter("detinator");
            if (id1 != null) {
                jb.connect();
                jb.adaugaDosar(java.lang.Integer.parseInt(id1), java.lang.Integer.parseInt(id2), datacreare, detinator);
                jb.disconnect();

        
      out.write("\n");
      out.write("         <div class=\"py-5\" >\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12 bg-dark text-light\">\n");
      out.write("          <h4 class=\"\">Datele au fost adaugate cu succes <span class=\"badge badge-pill badge-success\">!</span></h4>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("         <div class=\"py-5\" >\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12 mb-4\" ><a class=\"btn btn-primary\" href=\"index.html\">Home</a></div>\n");
      out.write("        <div class=\"col-md-12\"><a class=\"btn btn-primary\" href=\"tabela_Dosar.jsp\">Vizualizare tabela dosar</a></div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("  </div>");

        } else {
jb.connect();
        ResultSet rs1 = jb.vedeTabela("angajati");
        ResultSet rs2 = jb.vedeTabela("reviewuri");

        
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("          <div class=\"py-5\" >\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("        \n");
      out.write("        <form action=\"nou_Dosar.jsp\" method=\"post\">\n");
      out.write("            \n");
      out.write("     \n");
      out.write("<table>\n");
      out.write("                <tr>\n");
      out.write("                  <div class=\"form-group row\"><label for=\"inputNumeh\" class=\"col-2 col-form-label text-light bg-dark\">IdAngajat :</label>\n");
      out.write("                        \n");
      out.write("                    \n");
      out.write("                        \n");
      out.write("\t\t\t<SELECT NAME=\"idangajat\">\n");
      out.write("                                ");

                                    while(rs1.next()){
                                        idangajat = rs1.getInt("idangajat");
                                        NumeAngajat = rs1.getString("Nume");
                                        PrenumeAngajat = rs1.getString("Prenume");
                                        Firma= rs1.getString("Firma");
                                        Experienta= rs1.getString("Experienta");
                                
      out.write("\n");
      out.write("                                <OPTION VALUE=\"");
      out.print( idangajat);
      out.write('"');
      out.write('>');
      out.print( idangajat);
      out.write(',');
      out.print( NumeAngajat);
      out.write(',');
      out.print( PrenumeAngajat);
      out.write(',');
      out.print( Firma);
      out.write(',');
      out.print( Experienta);
      out.write("</OPTION>\n");
      out.write("                                ");

                                    }
                                
      out.write("\n");
      out.write("\t\t\t</SELECT>\n");
      out.write("                    \n");
      out.write("                  </div>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <div class=\"form-group row\"><label for=\"inputNumeh\" class=\"col-2 col-form-label text-light bg-dark\">IdReview :</label>\n");
      out.write("                   \n");
      out.write("                        \n");
      out.write("\t\t\t<SELECT NAME=\"idreview\">\n");
      out.write("\t\t\t\t<!-- OPTION selected=\"yes\" VALUE=\"iris1\">Iris 1</OPTION -->\n");
      out.write("                                ");

                                    while(rs2.next()){
                                        idreview = rs2.getInt("idreview");
                                        tipReview = rs2.getString("tipreview");
                                        comentariiReview = rs2.getString("comentarii");
                                
      out.write("\n");
      out.write("                                    <OPTION VALUE=\"");
      out.print( idreview);
      out.write('"');
      out.write('>');
      out.print( idreview);
      out.write(',');
      out.print( tipReview);
      out.write(',');
      out.print( comentariiReview);
      out.write("</OPTION>\n");
      out.write("                                ");

                                    }
                                
      out.write("\n");
      out.write("\t\t\t</SELECT>\n");
      out.write("                    </div>\n");
      out.write("                </tr>\n");
      out.write("                <div class=\"form-group row\"><label for=\"inputdatacreareh\" class=\"col-2 col-form-label text-light bg-dark\">Data Creare :</label>\n");
      out.write("                        <div class=\"col-10\"><input class=\"form-control\" type=\"text\" name=\"datacreare\"  placeholder=\"placeholder\" /></div></div>\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                <div class=\"form-group row\"><label for=\"inputdetinatorh\" class=\"col-2 col-form-label text-light bg-dark\">Detinator :</label>\n");
      out.write("                        <div class=\"col-10\"><input class=\"form-control\" type=\"text\" name=\"detinator\"  placeholder=\"placeholder\" /></div></div>\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("            <input class=\"btn btn-primary\" type=\"submit\" value=\"Adauga dosarul\" />\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("    \n");
      out.write("                       </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("        \n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
